global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "backend"
    dns_sd_configs:
      - names:
          - "tasks.unitrack-backend"
        type: A
        port: 5086
    metrics_path: "/metrics"
